package com.taxisurfr.manager;

import com.taxisurfr.domain.Ip2nationCountries;

import javax.ejb.Stateless;
import java.util.logging.Logger;

import static com.taxisurfr.domain.Ip2nationCountries.create;

@Stateless
public class Ip2NationCountriesManager extends AbstractDao<Ip2nationCountries> {
    private static final Logger logger = Logger.getLogger(Ip2NationCountriesManager.class.getName());

    public Ip2NationCountriesManager() {
        super(Ip2nationCountries.class);
    }

    public void setup(){
        deleteAll();
        persist(create("ad", "AD", "AND", "Andorra", "Andorra", 42.3, 1.3));
        persist(create("ae", "AE", "ARE", "United Arab Emirates", "United Arab Emirates", 24, 54));
        persist(create("af", "AF", "AFG", "Afghanistan", "Afghanistan", 33, 65));
        persist(create("ag", "AG", "ATG", "Antigua and Barbuda", "Antigua and Barbuda", 17.03, -61.48));
        persist(create("ai", "AI", "AIA", "Anguilla", "Anguilla", 18.15, -63.1));
        persist(create("al", "AL", "ALB", "Albania", "Albania", 41, 20));
        persist(create("am", "AM", "ARM", "Armenia", "Armenia", 40, 45));
        persist(create("an", "AN", "ANT", "Netherlands Antilles", "Netherlands Antilles", 12.15, -68.45));
        persist(create("ao", "AO", "AGO", "Angola", "Angola", -12.3, 18.3));
        persist(create("aq", "AQ", "ATA", "Antarctica", "Antarctica", -90, 0));
        persist(create("ar", "AR", "ARG", "Argentina", "Argentina", -34, -64));
        persist(create("as", "AS", "ASM", "American Samoa", "American Samoa", -14.2, -170));
        persist(create("at", "AT", "AUT", "Austria", "Austria", 47.2, 13.2));
        persist(create("au", "AU", "AUS", "Australia", "Australia", -27, 133));
        persist(create("aw", "AW", "ABW", "Aruba", "Aruba", 12.3, -69.58));
        persist(create("az", "AZ", "AZE", "Azerbaijan", "Azerbaijan", 40.3, 47.3));
        persist(create("ba", "BA", "BIH", "Bosnia and Herzegovina", "Bosnia and Herzegovina", 44, 18));
        persist(create("bb", "BB", "BRB", "Barbados", "Barbados", 13.1, -59.32));
        persist(create("bd", "BD", "BGD", "Bangladesh", "Bangladesh", 24, 90));
        persist(create("be", "BE", "BEL", "Belgium", "Belgium", 50.5, 4));
        persist(create("bf", "BF", "BFA", "Burkina Faso", "Burkina Faso", 13, -2));
        persist(create("bg", "BG", "BGR", "Bulgaria", "Bulgaria", 43, 25));
        persist(create("bh", "BH", "BHR", "Bahrain", "Bahrain", 26, 50.33));
        persist(create("bi", "BI", "BDI", "Burundi", "Burundi", -3.3, 30));
        persist(create("bj", "BJ", "BEN", "Benin", "Benin", 9.3, 2.15));
        persist(create("bm", "BM", "BMU", "Bermuda", "Bermuda", 32.2, -64.45));
        persist(create("bn", "BN", "BRN", "Brunei Darussalam", "Brunei Darussalam", 4.3, 114.4));
        persist(create("bo", "BO", "BOL", "Bolivia (Plurinational State of)", "Bolivia", -17, -65));
        persist(create("br", "BR", "BRA", "Brazil", "Brazil", -10, -55));
        persist(create("bs", "BS", "BHS", "Bahamas", "Bahamas", 24.15, -76));
        persist(create("bt", "BT", "BTN", "Bhutan", "Bhutan", 27.3, 90.3));
        persist(create("bv", "BV", "BVT", "Bouvet Island", "Bouvet Island", -54.26, 3.24));
        persist(create("bw", "BW", "BWA", "Botswana", "Botswana", -22, 24));
        persist(create("by", "BY", "BLR", "Belarus", "Belarus", 53, 28));
        persist(create("bz", "BZ", "BLZ", "Belize", "Belize", 17.15, -88.45));
        persist(create("ca", "CA", "CAN", "Canada", "Canada", 60, -95));
        persist(create("cc", "CC", "CCK", "Cocos (Keeling) Islands", "Cocos (Keeling) Islands", -12.3, 96.5));
        persist(create("cf", "CF", "CAF", "Central African Republic", "Central African Republic", 7, 21));
        persist(create("cg", "CG", "COG", "Congo", "Congo", 0, 25));
        persist(create("ch", "CH", "CHE", "Switzerland", "Switzerland", 47, 8));
        persist(create("ck", "CK", "COK", "Cook Islands", "Cook Islands", -21.14, -159.46));
        persist(create("cl", "CL", "CHL", "Chile", "Chile", -30, -71));
        persist(create("cm", "CM", "CMR", "Cameroon", "Cameroon", 6, 12));
        persist(create("cn", "CN", "CHN", "China", "China", 35, 105));
        persist(create("co", "CO", "COL", "Colombia", "Colombia", 4, -72));
        persist(create("cr", "CR", "CRI", "Costa Rica", "Costa Rica", 10, -84));
        persist(create("cs", "SC", "SCG", "Serbia and Montenegro", "Serbia and Montenegro", 43.57, 21.41));
        persist(create("cu", "CU", "CUB", "Cuba", "Cuba", 21.3, -80));
        persist(create("cv", "CV", "CPV", "Cabo Verde", "Cape Verde", 16, -24));
        persist(create("cx", "CX", "CXR", "Christmas Island", "Christmas Island", -10.3, 105.4));
        persist(create("cy", "CY", "CYP", "Cyprus", "Cyprus", 35, 33));
        persist(create("cz", "CZ", "CZE", "Czech Republic", "Czech Republic", 49.45, 15.3));
        persist(create("de", "DE", "DEU", "Germany", "Germany", 51, 9));
        persist(create("dj", "DJ", "DJI", "Djibouti", "Djibouti", 11.3, 43));
        persist(create("dk", "DK", "DNK", "Denmark", "Denmark", 56, 10));
        persist(create("dm", "DM", "DMA", "Dominica", "Dominica", 15.25, -61.2));
        persist(create("do", "DO", "DOM", "Dominican Republic", "Dominican Republic", 19, -70.4));
        persist(create("dz", "DZ", "DZA", "Algeria", "Algeria", 28, 3));
        persist(create("ec", "EC", "ECU", "Ecuador", "Ecuador", -2, -77.3));
        persist(create("ee", "EE", "EST", "Estonia", "Estonia", 59, 26));
        persist(create("eg", "EG", "EGY", "Egypt", "Egypt", 27, 30));
        persist(create("eh", "EH", "ESH", "Western Sahara", "Western Sahara", 24.3, -13));
        persist(create("er", "ER", "ERI", "Eritrea", "Eritrea", 15, 39));
        persist(create("es", "ES", "ESP", "Spain", "Spain", 40, -4));
        persist(create("et", "ET", "ETH", "Ethiopia", "Ethiopia", 8, 38));
        persist(create("fi", "FI", "FIN", "Finland", "Finland", 64, 26));
        persist(create("fj", "FJ", "FJI", "Fiji", "Fiji", -18, 175));
        persist(create("fk", "FK", "FLK", "Falkland Islands (Malvinas)", "Falkland Islands (Malvinas)", -51.45, -59));
        persist(create("fm", "FM", "FSM", "Micronesia (Federated States of)", "Micronesia", 6.55, 158.15));
        persist(create("fo", "FO", "FRO", "Faroe Islands", "Faroe Islands", 62, -7));
        persist(create("fr", "FR", "FRA", "France", "France", 46, 2));
        persist(create("ci", "CI", "CIV", "Côte d\"Ivoire", "Ivory Coast", 7.64, -4.93));
        persist(create("ga", "GA", "GAB", "Gabon", "Gabon", -1, 11.45));
        persist(create("gd", "GD", "GRD", "Grenada", "Grenada", 12.07, -61.4));
        persist(create("ge", "GE", "GEO", "Georgia", "Georgia", 42, 43.3));
        persist(create("gf", "GF", "GUF", "French Guiana", "French Guiana", 4, -53));
        persist(create("gh", "GH", "GHA", "Ghana", "Ghana", 8, -2));
        persist(create("gi", "GI", "GIB", "Gibraltar", "Gibraltar", 36.8, -5.21));
        persist(create("gl", "GL", "GRL", "Greenland", "Greenland", 72, -40));
        persist(create("gm", "GM", "GMB", "Gambia", "Gambia", 13.28, -16.34));
        persist(create("gn", "GN", "GIN", "Guinea", "Guinea", 11, -10));
        persist(create("gp", "GP", "GLP", "Guadeloupe", "Guadeloupe", 16.15, -61.35));
        persist(create("gq", "GQ", "GNQ", "Equatorial Guinea", "Equatorial Guinea", 2, 10));
        persist(create("gr", "GR", "GRC", "Greece", "Greece", 39, 22));
        persist(create("gs", "GS", "SGS", "South Georgia and the South Sandwich Islands", "S. Georgia and S. Sandwich Isls.", -54.3, -37));
        persist(create("gt", "GT", "GTM", "Guatemala", "Guatemala", 15.3, -90.15));
        persist(create("gu", "GU", "GUM", "Guam", "Guam", 13.28, 144.47));
        persist(create("gw", "GW", "GNB", "Guinea-Bissau", "Guinea-Bissau", 12, -15));
        persist(create("gy", "GY", "GUY", "Guyana", "Guyana", 5, -59));
        persist(create("hk", "HK", "HKG", "Hong Kong", "Hong Kong", 22.15, 114.1));
        persist(create("hm", "HM", "HMD", "Heard Island and McDonald Islands", "Heard and McDonald Islands", -53.06, 72.31));
        persist(create("hn", "HN", "HND", "Honduras", "Honduras", 15, -86.3));
        persist(create("hr", "HR", "HRV", "Croatia", "Croatia (Hrvatska)", 45.1, 15.3));
        persist(create("ht", "HT", "HTI", "Haiti", "Haiti", 19, -72.25));
        persist(create("hu", "HU", "HUN", "Hungary", "Hungary", 47, 20));
        persist(create("id", "ID", "IDN", "Indonesia", "Indonesia", -5, 120));
        persist(create("ie", "IE", "IRL", "Ireland", "Ireland", 53, -8));
        persist(create("il", "IL", "ISR", "Israel", "Israel", 31.3, 34.45));
        persist(create("in", "IN", "IND", "India", "India", 20, 77));
        persist(create("io", "IO", "IOT", "British Indian Ocean Territory", "British Indian Ocean Territory", -6, 71.3));
        persist(create("iq", "IQ", "IRQ", "Iraq", "Iraq", 33, 44));
        persist(create("ir", "IR", "IRN", "Iran (Islamic Republic of)", "Iran", 32, 53));
        persist(create("is", "IS", "ISL", "Iceland", "Iceland", 65, -18));
        persist(create("it", "IT", "ITA", "Italy", "Italy", 42.5, 12.5));
        persist(create("jm", "JM", "JAM", "Jamaica", "Jamaica", 18.15, -77.3));
        persist(create("jo", "JO", "JOR", "Jordan", "Jordan", 31, 36));
        persist(create("jp", "JP", "JPN", "Japan", "Japan", 36, 138));
        persist(create("ke", "KE", "KEN", "Kenya", "Kenya", 1, 38));
        persist(create("kg", "KG", "KGZ", "Kyrgyzstan", "Kyrgyzstan", 41, 75));
        persist(create("kh", "KH", "KHM", "Cambodia", "Cambodia", 13, 105));
        persist(create("ki", "KI", "KIR", "Kiribati", "Kiribati", 1.25, 173));
        persist(create("km", "KM", "COM", "Comoros", "Comoros", -12.1, 44.15));
        persist(create("kn", "KN", "KNA", "Saint Kitts and Nevis", "Saint Kitts and Nevis", 17.2, -62.45));
        persist(create("kp", "KP", "PRK", "Korea (Democratic People\"s Republic of)", "Korea (North)", 40, 127));
        persist(create("kr", "KR", "KOR", "Korea (Republic of)", "Korea (South)", 37, 127.3));
        persist(create("kw", "KW", "KWT", "Kuwait", "Kuwait", 29.3, 45.45));
        persist(create("ky", "KY", "CYM", "Cayman Islands", "Cayman Islands", 19.3, -80.3));
        persist(create("kz", "KZ", "KAZ", "Kazakhstan", "Kazakhstan", 48, 68));
        persist(create("la", "LA", "LAO", "Lao People\"s Democratic Republic", "Laos", 18, 105));
        persist(create("lb", "LB", "LBN", "Lebanon", "Lebanon", 33.5, 35.5));
        persist(create("lc", "LC", "LCA", "Saint Lucia", "Saint Lucia", 13.53, -60.68));
        persist(create("li", "LI", "LIE", "Liechtenstein", "Liechtenstein", 47.16, 9.32));
        persist(create("lk", "LK", "LKA", "Sri Lanka", "Sri Lanka", 7, 81));
        persist(create("lr", "LR", "LBR", "Liberia", "Liberia", 6.3, -9.3));
        persist(create("ls", "LS", "LSO", "Lesotho", "Lesotho", -29.3, 28.3));
        persist(create("lt", "LT", "LTU", "Lithuania", "Lithuania", 56, 24));
        persist(create("lu", "LU", "LUX", "Luxembourg", "Luxembourg", 49.45, 6.1));
        persist(create("lv", "LV", "LVA", "Latvia", "Latvia", 57, 25));
        persist(create("ly", "LY", "LBY", "Libya", "Libya", 25, 17));
        persist(create("ma", "MA", "MAR", "Morocco", "Morocco", 32, -5));
        persist(create("mc", "MC", "MCO", "Monaco", "Monaco", 43.44, 7.24));
        persist(create("md", "MD", "MDA", "Moldova (Republic of)", "Moldova", 47, 29));
        persist(create("mg", "MG", "MDG", "Madagascar", "Madagascar", -20, 47));
        persist(create("mh", "MH", "MHL", "Marshall Islands", "Marshall Islands", 9, 168));
        persist(create("mk", "MK", "MKD", "Macedonia (the former Yugoslav Republic of)", "Macedonia", 41.5, 22));
        persist(create("ml", "ML", "MLI", "Mali", "Mali", 17, -4));
        persist(create("mm", "MM", "MMR", "Myanmar", "Burma (Myanmar)", 22, 98));
        persist(create("mn", "MN", "MNG", "Mongolia", "Mongolia", 46, 105));
        persist(create("mo", "MO", "MAC", "Macao", "Macau", 22.1, 113.33));
        persist(create("mp", "MP", "MNP", "Northern Mariana Islands", "Northern Mariana Islands", 15.12, 145.45));
        persist(create("mq", "MQ", "MTQ", "Martinique", "Martinique", 14.4, -61));
        persist(create("mr", "MR", "MRT", "Mauritania", "Mauritania", 20, -12));
        persist(create("ms", "MS", "MSR", "Montserrat", "Montserrat", 16.45, -62.12));
        persist(create("mt", "MT", "MLT", "Malta", "Malta", 35.5, 14.35));
        persist(create("mu", "MU", "MUS", "Mauritius", "Mauritius", -20.17, 57.33));
        persist(create("mv", "MV", "MDV", "Maldives", "Maldives", 3.15, 73));
        persist(create("mw", "MW", "MWI", "Malawi", "Malawi", -13.3, 34));
        persist(create("mx", "MX", "MEX", "Mexico", "Mexico", 23, -102));
        persist(create("my", "MY", "MYS", "Malaysia", "Malaysia", 2.3, 112.3));
        persist(create("mz", "MZ", "MOZ", "Mozambique", "Mozambique", -18.15, 35));
        persist(create("na", "NA", "NAM", "Namibia", "Namibia", -22, 17));
        persist(create("nc", "NC", "NCL", "New Caledonia", "New Caledonia", -21.3, 165.3));
        persist(create("ne", "NE", "NER", "Niger", "Niger", 16, 8));
        persist(create("nf", "NF", "NFK", "Norfolk Island", "Norfolk Island", -29.02, 167.57));
        persist(create("ng", "NG", "NGA", "Nigeria", "Nigeria", 10, 8));
        persist(create("ni", "NI", "NIC", "Nicaragua", "Nicaragua", 13, -85));
        persist(create("nl", "NL", "NLD", "Netherlands", "Netherlands", 52.3, 5.45));
        persist(create("no", "NO", "NOR", "Norway", "Norway", 62, 10));
        persist(create("np", "NP", "NPL", "Nepal", "Nepal", 28, 84));
        persist(create("nr", "NR", "NRU", "Nauru", "Nauru", -0.32, 166.55));
        persist(create("nt", "NT", "NTZ", "Neutral Zone", "Neutral Zone", 0, 0));
        persist(create("nu", "NU", "NIU", "Niue", "Niue", -19.02, -169.52));
        persist(create("nz", "NZ", "NZL", "New Zealand", "New Zealand (Aotearoa)", -41, 174));
        persist(create("om", "OM", "OMN", "Oman", "Oman", 21, 57));
        persist(create("pa", "PA", "PAN", "Panama", "Panama", 9, -80));
        persist(create("pe", "PE", "PER", "Peru", "Peru", -10, -76));
        persist(create("pf", "PF", "PYF", "French Polynesia", "French Polynesia", -15, -140));
        persist(create("pg", "PG", "PNG", "Papua New Guinea", "Papua New Guinea", -6, 147));
        persist(create("ph", "PH", "PHL", "Philippines", "Philippines", 13, 122));
        persist(create("pk", "PK", "PAK", "Pakistan", "Pakistan", 30, 70));
        persist(create("pl", "PL", "POL", "Poland", "Poland", 52, 20));
        persist(create("pm", "PM", "SPM", "Saint Pierre and Miquelon", "St. Pierre and Miquelon", 46.5, -56.2));
        persist(create("pn", "PN", "PCN", "Pitcairn", "Pitcairn", -25.04, -130.06));
        persist(create("pr", "PR", "PRI", "Puerto Rico", "Puerto Rico", 18.15, -66.3));
        persist(create("pt", "PT", "PRT", "Portugal", "Portugal", 39.3, -8));
        persist(create("pw", "PW", "PLW", "Palau", "Palau", 7.3, 134.3));
        persist(create("py", "PY", "PRY", "Paraguay", "Paraguay", -23, -58));
        persist(create("qa", "QA", "QAT", "Qatar", "Qatar", 25.3, 51.15));
        persist(create("re", "RE", "REU", "Réunion", "Reunion", -21.06, 55.36));
        persist(create("ro", "RO", "ROU", "Romania", "Romania", 46, 25));
        persist(create("ru", "RU", "RUS", "Russian Federation", "Russia", 60, 100));
        persist(create("rw", "RW", "RWA", "Rwanda", "Rwanda", -2, 30));
        persist(create("sa", "SA", "SAU", "Saudi Arabia", "Saudi Arabia", 25, 45));
        persist(create("sb", "SB", "SLB", "Solomon Islands", "Solomon Islands", -8, 159));
        persist(create("sc", "SC", "SYC", "Seychelles", "Seychelles", -4.35, 55.4));
        persist(create("sd", "SD", "SDN", "Sudan", "Sudan", 15, 30));
        persist(create("se", "SE", "SWE", "Sweden", "Sweden", 62, 15));
        persist(create("sg", "SG", "SGP", "Singapore", "Singapore", 1.22, 103.48));
        persist(create("sh", "SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", "St. Helena", -15.56, -5.42));
        persist(create("si", "SI", "SVN", "Slovenia", "Slovenia", 46.07, 14.49));
        persist(create("sj", "SJ", "SJM", "Svalbard and Jan Mayen", "Svalbard and Jan Mayen Islands", 78, 20));
        persist(create("sk", "SK", "SVK", "Slovakia", "Slovak Republic", 48.4, 19.3));
        persist(create("sl", "SL", "SLE", "Sierra Leone", "Sierra Leone", 8.3, -11.3));
        persist(create("sm", "SM", "SMR", "San Marino", "San Marino", 43.46, 12.25));
        persist(create("sn", "SN", "SEN", "Senegal", "Senegal", 14, -14));
        persist(create("so", "SO", "SOM", "Somalia", "Somalia", 10, 49));
        persist(create("sr", "SR", "SUR", "Suriname", "Suriname", 4, -56));
        persist(create("st", "ST", "STP", "Sao Tome and Principe", "Sao Tome and Principe", 1, 7));
        persist(create("sv", "SV", "SLV", "El Salvador", "El Salvador", 13.5, -88.55));
        persist(create("sy", "SY", "SYR", "Syrian Arab Republic", "Syrian Arab Republic", 34.81, 39.05));
        persist(create("sz", "SZ", "SWZ", "Swaziland", "Swaziland", -26.3, 31.3));
        persist(create("tc", "TC", "TCA", "Turks and Caicos Islands", "Turks and Caicos Islands", 21.45, -71.35));
        persist(create("td", "TD", "TCD", "Chad", "Chad", 15, 19));
        persist(create("tf", "TF", "ATF", "French Southern Territories", "French Southern Territories", -43, 67));
        persist(create("tg", "TG", "TGO", "Togo", "Togo", 8, 1.1));
        persist(create("th", "TH", "THA", "Thailand", "Thailand", 15, 100));
        persist(create("tj", "TJ", "TJK", "Tajikistan", "Tajikistan", 39, 71));
        persist(create("tk", "TK", "TKL", "Tokelau", "Tokelau", -9, -172));
        persist(create("tm", "TM", "TKM", "Turkmenistan", "Turkmenistan", 40, 60));
        persist(create("tn", "TN", "TUN", "Tunisia", "Tunisia", 34, 9));
        persist(create("to", "TO", "TON", "Tonga", "Tonga", -20, -175));
        persist(create("tl", "TL", "TLS", "Timor-Leste", "East Timor", -8.5, 125.55));
        persist(create("tr", "TR", "TUR", "Turkey", "Turkey", 39, 35));
        persist(create("tt", "TT", "TTO", "Trinidad and Tobago", "Trinidad and Tobago", 11, -61));
        persist(create("tv", "TV", "TUV", "Tuvalu", "Tuvalu", -8, 178));
        persist(create("tw", "TW", "TWN", "Taiwan, Province of China", "Taiwan", 23.3, 121));
        persist(create("tz", "TZ", "TZA", "Tanzania, United Republic of", "Tanzania", -6, 35));
        persist(create("ua", "UA", "UKR", "Ukraine", "Ukraine", 49, 32));
        persist(create("ug", "UG", "UGA", "Uganda", "Uganda", 1, 32));
        persist(create("uk", "GB", "GBR", "United Kingdom of Great Britain and Northern Ireland", "United Kingdom", 54, -2));
        persist(create("us", "US", "USA", "United States of America", "United States", 38, -97));
        persist(create("uy", "UY", "URY", "Uruguay", "Uruguay", -33, -56));
        persist(create("uz", "UZ", "UZB", "Uzbekistan", "Uzbekistan", 41, 64));
        persist(create("va", "VA", "VAT", "Holy See", "Vatican City State (Holy See)", 41.54, 12.27));
        persist(create("vc", "VC", "VCT", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", 13.15, -61.12));
        persist(create("ve", "VE", "VEN", "Venezuela (Bolivarian Republic of)", "Venezuela", 8, -66));
        persist(create("vg", "VG", "VGB", "Virgin Islands (British)", "Virgin Islands (British)", 18.2, -64.5));
        persist(create("vi", "VI", "VIR", "Virgin Islands (U.S.)", "Virgin Islands (U.S.)", 18.2, -64.5));
        persist(create("vn", "VN", "VNM", "Viet Nam", "Viet Nam", 16, 106));
        persist(create("vu", "VU", "VUT", "Vanuatu", "Vanuatu", -16, 167));
        persist(create("wf", "WF", "WLF", "Wallis and Futuna", "Wallis and Futuna Islands", -13.18, -176.12));
        persist(create("ws", "WS", "WSM", "Samoa", "Samoa", -13.35, -172.2));
        persist(create("ye", "YE", "YEM", "Yemen", "Yemen", 15, 48));
        persist(create("yt", "YT", "MYT", "Mayotte", "Mayotte", -12.5, 45.1));
        persist(create("yu", "YU", "YUG", "Yugoslavia", "Yugoslavia", 44, 21));
        persist(create("za", "ZA", "ZAF", "South Africa", "South Africa", -29, 24));
        persist(create("zm", "ZM", "ZMB", "Zambia", "Zambia", -15, 30));
        persist(create("cd", "CD", "COD", "Congo (Democratic Republic of the)", "Democratic Republic of Congo", -4.04, 30.75));
        persist(create("zw", "ZW", "ZWE", "Zimbabwe", "Zimbabwe", -20, 30));
        persist(create("ap", "", "", "", "Asia-Pacific", -2.81, 128.5));
        persist(create("rs", "RS", "SRB", "Serbia", "Republic of Serbia", 44.02, 21.01));
        persist(create("ax", "AX", "ALA", "Åland Islands", "Aland Islands", 60.21, 20.16));
        persist(create("eu", "", "", "", "Europe", 0, 0));
        persist(create("01", "", "", "", "Private", 0, 0));
        persist(create("ps", "PS", "PSE", "Palestine, State of", "Palestinian Territory, Occupied", 31.89, 34.9));
        persist(create("me", "ME", "MNE", "Montenegro", "Montenegro", 42.74, 19.31));
        persist(create("bq", "BQ", "BES", "Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius and Saba", 12.16, -68.3));
        persist(create("cw", "CW", "CUW", "Cura�ao", "Cura�ao", 12.2, -68.94));
        persist(create("gg", "GG", "GGY", "Guernsey", "Guernsey", 49.46, -2.58));
        persist(create("im", "IM", "IMN", "Isle of Man", "Isle of Man", 54.23, -4.57));
        persist(create("je", "JE", "JEY", "Jersey", "Jersey", 49.21, -2.13));
        persist(create("bl", "BL", "BLM", "Saint Barthélemy", "Saint Barth�lemy", 17.91, -62.83));
        persist(create("mf", "MF", "MAF", "Saint Martin (French part)", "Saint Martin (French part)", 17.91, -62.83));
        persist(create("sx", "SX", "SXM", "Sint Maarten (Dutch part)", "Sint Maarten (Dutch part)", 18.03, -63.1));
        persist(create("ss", "SS", "SSD", "South Sudan", "South Sudan", 18.03, -63.1));
        persist(create("um", "UM", "UMI", "United States Minor Outlying Islands", "United States Minor Outlying Islands", 19.3, 166.63));


    }
}
